In [17]:
#import pandas package and the dataset
import pandas as pd
df = pd.read_csv('netflix_titles.csv')

df.head(5)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

Package and dataset successfully imported

Preparing tables structure (blank) in PostgreSQL following df table structure. Before that, check value len in python for better value constrain in SQL. Find the max value each and set more in each column in SQL.

In [4]:
df.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='object')

In [3]:
max(df.show_id.str.len())

5

In [5]:
max(df.type.str.len())

7

In [6]:
max(df.title.str.len())

104

In [7]:
max(df.director.str.len())

208.0

In [8]:
max(df.cast.str.len())

nan

When nan appears, that might be because it is exist and consider as max value in len. Drop first.

In [9]:
max(df.cast.dropna().str.len())

771

In [10]:
max(df.country.str.len())

123.0

In [11]:
max(df.date_added.str.len())

19.0

In [13]:
max(df.rating.str.len())

8.0

In [14]:
max(df.duration.str.len())

10.0

In [15]:
max(df.listed_in.str.len())

79

In [16]:
max(df.description.str.len())

248

In [19]:
#import sql package
from sqlalchemy import create_engine

engine = create_engine("postgresql+psycopg2://postgres:???@???:???/netflix_db")

engine.connect()

connection settled!
Syntax create_engine("postgresql+psycpg2://user:password@host:server/table_name")

In [22]:
#check connection
pd.read_sql("SELECT 100;", engine)

   ?column?
0       100

If tested number appear, it works then.

In [23]:
#import dataset to sql
df.to_sql('netflix_raw', con = engine, index = False, if_exists = 'append')

807

In [28]:
#check imported dataset
pd.read_sql("SELECT COUNT(*) FROM netflix_raw;", engine)

   count
0   8807

In [31]:
#check df len
len(df)

8807

If number of count match with df row, import success! Go to SQL to Querying!